# Generated by Django 6.0.6 on 2026-07-01 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('upload_type', models.CharField(choices=[('ZIP', 'ZIP'), ('GITHUB', 'GitHub')], default='ZIP', max_length=20)),
                ('repository_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('EXTRACTING', 'Extracting'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size', models.BigIntegerField(default=0)),
                ('is_directory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
        ),
    ]
