# Generated by Django 6.0.6 on 2026-07-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
