# Generated by Django 6.0.6 on 2026-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_repositoryfile_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
