# Generated by Django 6.0.6 on 2026-07-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_repositoryfile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='projects.repositoryfile')),
            ],
        ),
        migrations.CreateModel(
            name='CodeFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='projects.repositoryfile')),
            ],
        ),
        migrations.CreateModel(
            name='CodeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='projects.repositoryfile')),
            ],
        ),
    ]
