# Generated by Django 6.0.6 on 2026-07-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeintel', '0002_repositoryframework'),
        ('projects', '0003_repositoryfile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'key')},
            },
        ),
    ]
