# Generated by Django 6.0.6 on 2026-07-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeintel', '0003_repositorymetadata'),
        ('projects', '0003_repositoryfile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
