# Generated by Django 6.0.6 on 2026-07-04 03:51

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_repositoryfile_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('provider', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('dimensions', models.PositiveIntegerField(default=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='projects.project')),
            ],
            options={
                'db_table': 'knowledge_embeddings',
                'ordering': ['-created_at'],
            },
        ),
    ]
